name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest/googletest
        sudo cmake -S . -B build
        sudo cmake --build build
        sudo cp build/lib/*.a /usr/lib

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure
